# Generated by Django 4.2.2 on 2023-07-04 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogconn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogconn.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 4, 21, 1, 17, 468923)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 4, 21, 1, 17, 472929)),
        ),
    ]
