# Generated by Django 4.2.2 on 2023-07-05 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogconn', '0002_comment_parent_comment_alter_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='no_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 20, 48, 11, 806379)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 20, 48, 11, 806379)),
        ),
    ]
