# Generated by Django 4.2.2 on 2023-07-05 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogconn', '0004_rename_bio_profile_about_remove_profile_blogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 23, 29, 14, 416538)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 23, 29, 14, 416538)),
        ),
    ]
