# Generated by Django 4.2.2 on 2023-07-05 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogconn', '0005_remove_profile_gender_alter_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 23, 40, 26, 486828)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 23, 40, 26, 486828)),
        ),
    ]
