# Generated by Django 4.2.2 on 2023-07-11 00:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogconn', '0010_alter_comment_date_added_alter_uploads_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 28, 59, 227341)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 28, 59, 227341)),
        ),
    ]
